language: python
dist: xenial
sudo: true
python:
  - 3.8.2
services:
  postgresql
addons:
  postgresql: '9.5'
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -q pipenv
  - pipenv sync --dev
  - pipenv install -d codecov
  - cp contrib/env-sample .env
before_script:
  - psql -c "CREATE DATABASE testdb;" -U postgres
script:
  - pipenv run pytest --cov phsw_site
after_success:
  - pipenv run codecov