from rest_framework import serializers


class CamposBoletoSerializer(serializers.Serializer):
    banco = serializers.CharField()
    codigo_banco = serializers.CharField()
    linha_digitavel = serializers.CharField()
    codigo_barras = serializers.CharField()
    CNPJ_beneficiario = serializers.CharField()
    beneficiario = serializers.CharField()
    agencia = serializers.CharField()
    codigo_cedente = serializers.CharField()
    endereco_beneficiario = serializers.CharField()
    pagador = serializers.CharField()
    nosso_numero = serializers.CharField()
    documento = serializers.CharField()
    parcela = serializers.CharField()
    vencimento = serializers.CharField()
    valor_documento = serializers.CharField()
    local_pagamento = serializers.CharField()
    codigo_beneficiario = serializers.CharField()
    especie_documento = serializers.CharField()
    aceite = serializers.CharField()
    data_processamento = serializers.CharField()
    carteira = serializers.CharField()
    quantidade = serializers.CharField(allow_blank=True)
    xvalor = serializers.CharField(allow_blank=True)
    especie = serializers.CharField(allow_blank=True)
    instrucoes_responsabilidade = serializers.CharField()
    desconto_abatimento = serializers.CharField(allow_blank=True)
    outras_deducoes = serializers.CharField(allow_blank=True)
    mora_multa = serializers.CharField(allow_blank=True)
    outros_acrescimos = serializers.CharField(allow_blank=True)
    valor_cobrado = serializers.CharField(allow_blank=True)
    CNPJ_pagador = serializers.CharField()
    endereco_pagador = serializers.CharField()


class BoletoSerializer(serializers.Serializer):
    comando = serializers.CharField(max_length=15)
    modelo = serializers.CharField(max_length=15)
    campos = CamposBoletoSerializer()
