# Generated by Django 3.2.7 on 2021-09-17 11:28

from django.db import migrations, models
import django.utils.timezone
import django_cpf_cnpj.fields
import phsw_site.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('cpf', django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, verbose_name='CPF')),
                ('is_agente_admin', models.BooleanField(default=False)),
                ('all_api_permissions', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', phsw_site.base.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=60, verbose_name='Empresa')),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('codigo_cliente', models.CharField(blank=True, max_length=9, verbose_name='Código do cliente')),
                ('codigo_vendedor', models.CharField(blank=True, max_length=9, verbose_name='Código do vendedor')),
                ('statusEmpresa', models.CharField(choices=[('A', 'Ativado'), ('D', 'Desativado'), ('B', 'Bloqueado')], max_length=1)),
                ('tipoEmpresa', models.CharField(choices=[('D', 'Distribuidora'), ('L', 'Lojista'), ('O', 'Outros')], max_length=1)),
            ],
        ),
    ]
