# Generated by Django 3.2.6 on 2021-08-05 13:38

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default='sem descrição')),
                ('verbose_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('verbose_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=60)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18)),
                ('codigo_cliente', models.PositiveIntegerField(blank=True)),
                ('codigo_vendedor', models.PositiveIntegerField(blank=True)),
                ('fk_statusEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.statusempresa')),
            ],
        ),
    ]
