# Generated by Django 3.2.6 on 2021-08-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
        ('base', '0003_auto_20210805_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fk_tabelaPreco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.tabelapreco'),
        ),
    ]
