# Generated by Django 3.2.6 on 2021-08-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_empresa_fk_tabelapreco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo_vendedor',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
