# Generated by Django 3.2.6 on 2021-08-12 17:16

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20210812_1359'),
        ('base', '0005_auto_20210812_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=9, verbose_name='Código do cliente'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo_vendedor',
            field=models.CharField(blank=True, max_length=9, verbose_name='Código do vendedor'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fk_statusEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.statusempresa', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fk_tabelaPreco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.tabelapreco', verbose_name='Tabela preço'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fk_tipoEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.tipoempresa', verbose_name='Tipo de empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(max_length=60, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='statusempresa',
            name='descricao',
            field=models.TextField(default='sem descrição', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='statusempresa',
            name='verbose_name',
            field=models.CharField(max_length=15, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipoempresa',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipoempresa',
            name='verbose_name',
            field=models.CharField(max_length=15, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14, verbose_name='CPF'),
        ),
    ]
