# Generated by Django 3.2.6 on 2021-08-12 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210812_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fk_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.empresa', verbose_name='Empresa'),
        ),
    ]
