# Generated by Django 3.2.6 on 2021-08-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_fk_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agente_admin',
            field=models.BooleanField(default=False),
        ),
    ]
