# Generated by Django 3.2.7 on 2021-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_is_agente_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='all_api_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
