# Generated by Django 3.2.6 on 2021-08-05 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_auto_20210805_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id_categoria', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descricao', models.TextField(default='sem descrição')),
                ('verbose_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('verbose_name', models.CharField(max_length=50)),
                ('descricao', models.TextField(default='sem descrição')),
                ('unidade', models.CharField(max_length=10)),
                ('codigo_barras', models.IntegerField()),
                ('ativado', models.BooleanField()),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('fk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.item')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default='sem descrição')),
                ('verbose_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id_tabela', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('verbose_name', models.CharField(max_length=50)),
                ('itens', models.ManyToManyField(through='pedidos.ItemPreco', to='pedidos.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_faturamento', models.DateTimeField(blank=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empresa')),
                ('fk_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.statuspedido')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.item')),
            ],
        ),
        migrations.AddField(
            model_name='itempreco',
            name='fk_tabelaPreco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tabelapreco'),
        ),
        migrations.AlterUniqueTogether(
            name='itempreco',
            unique_together={('fk_tabelaPreco', 'fk_item')},
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11)),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('fk_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.item')),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
            options={
                'unique_together': {('fk_pedido', 'fk_item')},
            },
        ),
    ]
