# Generated by Django 3.2.7 on 2021-09-17 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_categoria', models.CharField(max_length=8, unique=True)),
                ('descricao', models.TextField(default='sem descrição', verbose_name='Descrição')),
                ('verbose_name', models.CharField(max_length=15, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_item', models.CharField(max_length=15, unique=True)),
                ('verbose_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.TextField(default='sem descrição', verbose_name='Descrição')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('codigo_barras', models.CharField(max_length=13, verbose_name='Código de barras')),
                ('ativado', models.BooleanField(verbose_name='Ativado')),
                ('imagem', models.ImageField(default='imagens/itens/defaultimage.jpeg', upload_to='imagens/itens/')),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriaitem', verbose_name='Categoria')),
            ],
            options={
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='ItemPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço unitario')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('fk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.item', verbose_name='Item')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tabela', models.CharField(max_length=7, unique=True)),
                ('verbose_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('itens', models.ManyToManyField(through='pedidos.ItemPreco', to='pedidos.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Digitação'), ('1', 'Transferido'), ('2', 'Registrado'), ('3', 'Faturado'), ('5', 'Entregue'), ('9', 'Cancelado')], max_length=1)),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do pedido')),
                ('data_faturamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do faturamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor total')),
                ('fk_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.empresa', verbose_name='Empresa')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.AddField(
            model_name='itempreco',
            name='fk_tabelaPreco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.tabelapreco', verbose_name='Tabela de preço'),
        ),
        migrations.AlterUniqueTogether(
            name='itempreco',
            unique_together={('fk_tabelaPreco', 'fk_item')},
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade')),
                ('preco_unit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço unitario')),
                ('fk_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.item', verbose_name='Item')),
                ('fk_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
                'unique_together': {('fk_pedido', 'fk_item')},
            },
        ),
    ]
