# Generated by Django 3.2.7 on 2021-09-21 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempreco',
            name='fk_tabelaPreco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_preco', to='pedidos.tabelapreco', verbose_name='Tabela de preço'),
        ),
    ]
