# Generated by Django 3.2.7 on 2021-09-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_itempreco_fk_tabelapreco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempreco',
            name='fk_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_code', to='pedidos.item', verbose_name='Item'),
        ),
    ]
