# Generated by Django 3.2.6 on 2021-08-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0002_alter_pedido_data_faturamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
