# Generated by Django 3.2.6 on 2021-08-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_fk_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_barras',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='item',
            name='fk_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.categoriaitem', verbose_name='Categoria'),
        ),
    ]
