# Generated by Django 3.2.6 on 2021-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20210812_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/itens/'),
        ),
    ]
