# Generated by Django 3.2.6 on 2021-08-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20210818_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(default='imagens/itens/defaultimage.jpeg', upload_to='imagens/itens/'),
        ),
    ]
