from rest_framework import serializers


class FieldsBoletoSerializer(serializers.Serializer):
    banco = serializers.CharField(max_length=15)
    codigo_banco = serializers.CharField(max_length=8, required=False)
    linha_digitavel = serializers.CharField(max_length=78)
    codigo_barras = serializers.CharField(max_length=44)
    CNPJ_beneficiario = serializers.CharField(max_length=18, required=False)
    beneficiario = serializers.CharField(max_length=92, required=False)
    agencia = serializers.CharField(max_length=12, required=False)
    codigo_cedente = serializers.CharField(max_length=14, required=False)
    endereco_beneficiario = serializers.CharField(max_length=98, required=False)
    pagador = serializers.CharField(max_length=91, required=False)
    nosso_numero = serializers.CharField(max_length=26, required=False)
    documento = serializers.CharField(max_length=20, required=False)
    parcela = serializers.CharField(max_length=26, required=False)
    vencimento = serializers.CharField(max_length=26, required=False)
    valor_documento = serializers.CharField(max_length=19, required=False)
    local_pagamento = serializers.CharField(max_length=108, required=False)
    codigo_beneficiario = serializers.CharField(max_length=17, required=False)
    especie_documento = serializers.CharField(max_length=12, required=False)
    aceite = serializers.CharField(max_length=7, required=False)
    data_processamento = serializers.CharField(max_length=16, required=False)
    data_documento = serializers.CharField(max_length=16, required=False)
    carteira = serializers.CharField(max_length=33, required=False)
    quantidade = serializers.CharField(allow_blank=True, max_length=22, required=False)
    xvalor = serializers.CharField(allow_blank=True, max_length=16, required=False)
    especie = serializers.CharField(allow_blank=True, max_length=11, required=False)
    instrucoes_responsabilidade_1 = serializers.CharField(max_length=95, required=False)
    instrucoes_responsabilidade_2 = serializers.CharField(max_length=95, required=False)
    instrucoes_responsabilidade_3 = serializers.CharField(max_length=95, required=False)
    instrucoes_responsabilidade_4 = serializers.CharField(max_length=95, required=False)
    instrucoes_responsabilidade_5 = serializers.CharField(max_length=95, required=False)
    instrucoes_responsabilidade_6 = serializers.CharField(max_length=95, required=False)
    instrucoes_responsabilidade_7 = serializers.CharField(max_length=95, required=False)
    instrucoes_responsabilidade_8 = serializers.CharField(max_length=95, required=False)
    desconto_abatimento = serializers.CharField(allow_blank=True, max_length=23, required=False)
    outras_deducoes = serializers.CharField(allow_blank=True, max_length=23, required=False)
    mora_multa = serializers.CharField(allow_blank=True, max_length=19, required=False)
    outros_acrescimos = serializers.CharField(allow_blank=True, max_length=19, required=False)
    valor_cobrado = serializers.CharField(allow_blank=True, max_length=22, required=False)
    CNPJ_pagador = serializers.CharField(max_length=16, required=False)
    endereco_pagador = serializers.CharField(max_length=171, required=False)


class BoletoSerializer(serializers.Serializer):
    comando = serializers.CharField(max_length=15)
    modelo = serializers.CharField(max_length=15)
    campos = FieldsBoletoSerializer()
